#!/bin/bash

random_str="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')";

if [ -s $HOME/.backgrounds ]
then
	rm -f $HOME/.backgrounds/*
fi

if [ ! -d $HOME/.backgrounds ]
then
	mkdir $HOME/.backgrounds
fi

if [ ! -d $HOME/.backgrounds/wget.log ]
then
	rm -f $HOME/.backgrounds/wget.log
fi


if [ $1 ]
then
	url="user/$1"
else
	url="random"
fi

wget -S https://source.unsplash.com/${url} -O $HOME/.backgrounds/${random_str}.jpg -q -o $HOME/.backgrounds/wget.log
source_file="$(cat $HOME/.backgrounds/wget.log | grep "Location" | sed -e 's/  Location: //g' -e 's/?ix.*//')"

picture_path="$HOME/.backgrounds/${random_str}.jpg";

# TESTED ON KDE PLASMA 5
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

qdbus org.kde.plasmashell /PlasmaShell evaluateScript "
	var allDesktops = desktops();
	desktop = allDesktops[0];
	desktop.wallpaperPlugin = \"org.kde.image\";
	desktop.currentConfigGroup = Array(\"Wallpaper\", \"org.kde.image\", \"General\");
	desktop.writeConfig(\"Image\", \"file://${picture_path}\")
"

echo "${source_file} ― enjoy!"
